version: '3.1'
services:
  app:
    container_name: springboot-simple-jwt
    image: springboot-simple-jwt
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - postgresqldb
  postgresqldb:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=senh@
      - POSTGRES_USER=postgres
      - POSTGRES_DB=estudos